### ISSUE TITLE
can not load model

### ISSUE THREAD

**Issue by iot-hunter** [simaiden/Clothes-Detection#2]
size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([14, 1024]) from checkpoint, the shape in current model is torch.Size([81, 1024]).
	size mismatch for roi_heads.box.predictor.cls_score.bias: copying a param with shape torch.Size([14]) from checkpoint, the shape in current model is torch.Size([81]).
	size mismatch for roi_heads.box.predictor.bbox_pred.weight: copying a param with shape torch.Size([56, 1024]) from checkpoint, the shape in current model is torch.Size([324, 1024]).
	size mismatch for roi_heads.box.predictor.bbox_pred.bias: copying a param with shape torch.Size([56]) from checkpoint, the shape in current model is torch.Size([324]).

**Comment by Aradhya0510** [comment]
@iot-hunter Hey, were you able to solve this issue?
